apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"  # every minute of the hour 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-job
            image: busybox
            command: ["sh", "-c", "echo $(date) >> /var/log/cronjob.log"]
          restartPolicy: OnFailure
